### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-2-evaluacion-intermedia-sandra1894#2]
Really cool job @sandra1894 !!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [ ] Extract the feedback painter to a function.
- [x] If we repeat several times `Number(value)` within a function it is better set it in a constant.

### JavaScript: advanced

- [ ] You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'?

### HTML

- [x] Use a `label` to define the content of the input.
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input.
- [ ] Use placeholder.
- [ ] Don't add an empty attribute for no special reason: by adding an empty `value` attribute we are indeed setting it to a certain (empty) value, do we want to do that?

### Steps to finish the game (for those far from the solution)

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables.
2. Generate the random number and save it to a variable.
3. Init counter of trials to 0.
4. Define a function that executes when the user clicks on the button, that

- increments the counter and paints its value in the HTML.
- collect the value of the HTML input and compare it with the random number.
  - if they are equal, draw a 'You Win' message.
  - if it's lower, draw a 'Too short' message.
  - if it's higher, draw a 'Too long' message.

5. Assign a listener to the button click to execute the previous function.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by sandra1894** [comment]
Hi Miguel,
I don't understand some issues:

- Extract the feedback painter to a function. - **You mean, that I have to introduce the console.log into the functions?**

- You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'? - **When I try to change, for example "writeAndTry.innerHTML" to a global constant, and put on the function answerNumber I have an error and I don't know why, could you help me, please? **

- Use placeholder. - **I'm using placeholder in the input class="main__number". Can you see it?**

- Don't add an empty attribute for no special reason: by adding an empty value attribute we are indeed setting it to a certain (empty) value, do we want to do that? - **I'm not adding empty atributes as value. Do you mean the atribute action to the form?**

I will wait your answer, thank you!

**Comment by migueldelmazo** [comment]
Hola @sandra1894, te voy contestando

> Extract the feedback painter to a function. - You mean, that I have to introduce the console.log into the functions?

> You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'? - When I try to change, for example "writeAndTry.innerHTML" to a global constant, and put on the function answerNumber I have an error and I don't know why, could you help me, please?

Las dos anteriores son la misma mejora. Sí tu haces muchas veces `writeAndTry.innerHTML =...` puedes moverlo dentro de una función que se llame por ejemplo `updateClue('Has ganado')`.

> Use placeholder. - I'm using placeholder in the input class="main__number". Can you see it?

Nos referimos a esto ` placeholder="Introduce un número..."` que no sé si lo tenías antes.

> Don't add an empty attribute for no special reason: by adding an empty value attribute we are indeed setting it to a certain (empty) value, do we want to do that?: No debemos dejar atributos vacíos como el `action=""` del form.

Gracias por el curro Sandra!!

**Comment by migueldelmazo** [comment]
Hola @sandra1894, te voy contestando

> Extract the feedback painter to a function. - You mean, that I have to introduce the console.log into the functions?

> You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'? - When I try to change, for example "writeAndTry.innerHTML" to a global constant, and put on the function answerNumber I have an error and I don't know why, could you help me, please?

Las dos anteriores son la misma mejora. Sí tu haces muchas veces `writeAndTry.innerHTML =...` puedes moverlo dentro de una función que se llame por ejemplo `updateClue('Has ganado')`.

> Use placeholder. - I'm using placeholder in the input class="main__number". Can you see it?

Nos referimos a esto ` placeholder="Introduce un número..."` que no sé si lo tenías antes.

> Don't add an empty attribute for no special reason: by adding an empty value attribute we are indeed setting it to a certain (empty) value, do we want to do that?: No debemos dejar atributos vacíos como el `action=""` del form.

Gracias por el curro Sandra!!
